config/routes.rb
Homecanvasr::Application.routes.draw do
  
  devise_for :users

  #agents
  match "/agents/welcome" => "agents#welcome"
  match "/agents" => "agents#welcome"

  root to:  "home#index"

  resources :posts
  resources :clients

end

app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :county_id, :city_code, :name
  belongs_to :county
end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :user_id, :last_name, :living_status, :move_timeframe, :preapproval_attributes
  belongs_to :user
  has_one :preapproval

  validates :user_id, :last_name, :living_status, :move_timeframe, presence: :true  

  accepts_nested_attributes_for :preapproval
end

app/models/county.rb
class County < ActiveRecord::Base
  attr_accessible :name, :state_id
  belongs_to :state
  has_many :cities
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :attached_garage, :state_id, :county_id, :city_code, :client_id, :max_price, :max_taxes, :min_price, :min_bath, :min_bed, :min_sq_ft, :pool, :user_id

  validates :client_id, :city_code, :state_id, :county_id, :max_price, :min_price, :max_taxes, :min_sq_ft, :presence => true
  
  belongs_to :user
  has_one :client

  def client_name
  	Client.where("id = ?", client_id) ? Client.where("id = ?", client_id).first.last_name : "Client Name"
  end

	def state_name
 		State.where("id = ?", state_id).first.name 
 	end

	def county_name
 		County.where("id = ?", county_id).first.name 
 	end

 	def city_name
 		City.where("city_code = ?", city_code).first.name 
 	end	

end

app/models/preapproval.rb
class Preapproval < ActiveRecord::Base
  attr_accessible :file_name 
  belongs_to :client
end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :name
  has_many :counties
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :posts
  has_many :clients
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
	#before_filter :authenticate_agent!
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
	
	def new 
		@client = Client.new
    @client.build_preapproval
	end

  def create
    @client = current_user.clients.new(params[:client])
    if @client.save
    	redirect_to clients_path, :notice => "New client added successfully"
    else
      redirect_to new_client_path, :notice => "Please fill out all fields"
    end
  end

  def index
    @clients = current_user.clients
  end

  def destroy
    @client = Client.find(params[:id])
    Client.destroy(params[:id])
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])
    @client.update_attributes(params[:client])
    if @client.save
      redirect_to clients_path
    end
  end
	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index

	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :authenticate_user!

	def new
		@post = current_user.posts.new
	end

  def create
    @post = current_user.posts.new(params[:post])
    if @post.save
      redirect_to posts_path, :notice => 'Post added successfully!'
    else
      redirect_to new_post_path, :notice => 'Please complete all fields'
    end
  end

  def index
    @user = current_user
    @posts = @user.posts
  end

  def destroy
    @post = Post.find(params[:id])
    Post.destroy(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    record = Post.find(params[:id])
    if record.update_attributes(params[:post])
      redirect_to posts_path
    end
  end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    @current_method = "new"

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/agents/index.html.erb
<a class="btn btn-info" href="#">Search Properties</a>
<br>
<br>
<br>
<ul class="nav nav-tabs">
  <li class="active">
  	<a href="#">Posts</a>
  </li>
  <li>
    <a href="#">Clients</a>
  </li>
  <li>
  	<a href="#">Favorites</a>
  </li>
</ul>

app/views/agents/new.html.erb
<h2>Sign Up</h2>

<%= form_for(@agent) do |a| %>

  <%= a.fields_for :user do |u| %>

  <div class="field">
    <%= u.label :email %><br />
    <%= u.text_field :email %>
  </div>
  <div class="field">
    <%= u.label :password %><br />
    <%= u.password_field :password %>
  </div>
  <div class="field">
    <%= u.label :password_confirmation %><br />
    <%= u.password_field :password_confirmation %>
  </div>
  <% end %>
  <div class="field">
    <%= a.label :first_name %><br />
    <%= a.text_field :first_name %>
  </div>
  <div class="field">
    <%= a.label :last_name %><br />
    <%= a.text_field :last_name %>
  </div>

 </br>
  
  <div class="actions">
    <%= a.submit %>
  </div>
<% end %>

app/views/agents/welcome.html.erb
<h2> Agent Welcome Page </h2>
<hr>
<h3> How It Works </h3>
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur condimentum tempus sapien, at egestas risus ornare vitae. Nulla viverra iaculis libero, eu egestas elit iaculis sit amet. Morbi ac luctus eros. Nulla adipiscing feugiat volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ultrices enim eu elit vehicula sit amet rutrum dui laoreet. Suspendisse scelerisque luctus neque nec tincidunt. Donec mi neque, mollis varius euismod vel, dictum quis sem. Etiam eros dolor, convallis eget faucibus eget, scelerisque dictum augue. Etiam euismod, mauris ac pharetra pulvinar, mi nunc interdum nulla, eget auctor nisl libero ac velit. Integer vestibulum laoreet ante imperdiet vulputate. Duis et justo tellus, sit amet aliquet neque.

</P>
<hr>
<!-- Post Share Search -->
<div class="row-fluid">
  <div class="span4">
    <h2>Post for Client</h2>
    <p>Provide your client's dream home criteria to current homeowners.</p>
  </div>
  <div class="span4">
    <h2>Search</h2>
    <p>Find "every" home in your home search not just the properties "on the market"</p>
  </div>
  <div class="span4">
    <h2>Trends</h2>
    <p>See activity and what's going on in an area</p>
  </div>
</div>
<div class="row-fluid">
  <div class="span4">
<a class="btn btn-large btn-info" href="/posts/new" >Post</a>
  </div>
  <div class="span4">
<a class="btn btn-large btn-info" href="/agents/welcome" >Search</a>
  </div>
  <div class="span4">
<a class="btn btn-large btn-info" href="/agents/welcome" >Trends</a>
  </div>
</div>

app/views/clients/destroy.js.erb
$("#client_<%= @client.id %>").hide();

app/views/clients/edit.html.erb
<%= form_for @client do |f| %>

	<label>Client Last Name</label><br />
	<%= f.text_field :last_name %><br />

	<label>Client Living Status</label><br />
	<%= f.select :living_status, ['Rents', 'Owns'] %><br />

	<label>Moving Timeframe</label><br />
	<%= f.select :move_timeframe, ['3 months', '6 months', '1 year', 'Not sure'] %><br />
  </br> 
  <%= f.submit "Update Client", class: "btn-info"%>

<% end %>

app/views/clients/index.html.erb
<h2>My Clients</h2>

</br>

<table class="table table-striped">

	<tr>
		<th>Client</th>
		<th>Date Added</th>
		<th>Current Status</th>
		<th>Move Timeframe</th>
		<th>Pre-approval Status</th>		
		<th>Pre-approval Amount</th>
		<th>Manage</th>
	</tr>

	<% @clients.each do |c| %>

	<tr id=<%="client_#{c.id}"%> >
		<td><%= c.last_name %></td>
		<td><%= c.created_at.to_date %></td>
		<td><%= c.living_status %></td>
		<td><%= c.move_timeframe %></td>
		<td>Pre approval status</td>
		<td>Pre approval amount</td>		
		<td><%= link_to "Delete", c, method: :delete, :confirm => "Sure you want to remove this client?", remote: :true %> | <%= link_to "Edit", edit_client_path(c) %> </td>
	</tr>

	<% end %>
	
</table>

<a class="btn btn btn-info" id="new_client" href="/clients/new" >Add New Client</a>

app/views/clients/new.html.erb
<h2>Add New Client</h2>

<%= form_for @client do |f| %>

	<label>Client Last Name</label><br />
	<%= f.text_field :last_name %><br />

	<label>Client Living Status</label><br />
	<%= f.select :living_status, ['Rents', 'Owns'] %><br />

	<label>Moving Timeframe</label><br />
	<%= f.select :move_timeframe, ['3 months', '6 months', '1 year', 'Not sure'] %><br />
  </br> 

  <%= f.fields_for :preapproval do |builder| %>
  	<fieldset>
  		<%= builder.label :file_name, "Preapproval File Name" %></br>
  		<%= builder.text_field :file_name %></br>
  	</fieldset>
  <% end %>
  </br>
  <%= f.submit "Add Client", class: "btn-info"%>
<% end %>

app/views/home/index.html.erb
<div class="hero-unit">
  <h1>Your Dream Home Awaits</h1>
  <p>I'm a...</p>
  <p>
    <div class="btn-group">
      <a class="btn btn-large btn-info" href="/agents/welcome" >Agent</a>
      <a class="btn btn-large btn-info" href="/users/sign_in">Buyer</a>
      <a class="btn btn-large btn-info" href="/users/sign_in">Homeowner</a>
    </div>
  </p>
</div>

<!-- Post Share Search -->
<div class="row-fluid">
  <div class="span12 offset4">
    <h1>How it works</h1>
  </div>
</div>

<hr>

<!-- Post Share Search -->
<div class="row-fluid">
  <div class="span4">
    <h2>Post</h2>
    <p>Provide your dream home criteria to current homeowners.</p>
  </div>
  <div class="span4">
    <h2>Share</h2>
    <p>Advertise your "dream" home criteria to the WORLD aka all the homeowners in your interested area</p>
 </div>
  <div class="span4">
    <h2>Search</h2>
    <p>Find "every" home in your home search not just the properties "on the market"</p>
  </div>
</div>

<hr>

<!-- Other -->
<div class="row-fluid">
  <div class="span4">
    <h3>About Us</h3>
      Our Mission |
      Our Team |
      Contact Us
  </div>
  <div class="span4">
    <h3>Follow Us</h3>
      <img src="assets/facebook.png" alt="facebook_icon">
      <img src="assets/twitter.png" alt="twitter_icon">
      <img src="assets/google.png" alt="facebook_icon">
  </div>
  <div class="span4">
    <h3>Fine Print</h3>
      Terms of Use |
      Privacy Policy
  </div>
</div>

<hr>
 
<!-- Post Share Search -->
<div class="row-fluid">
  <div class="span12 offset4">
    <p>&copy; HomeCanvasr 2013</p>
  </div>
</div>

app/views/home/main.html.erb
<div class="hero-unit">
  <h1>Your Dream Home Awaits</h1>
  <p>I'm a...</p>
  <p>
    <div class="btn-group">
      <button class="btn btn-large btn-info">Agent</button>
      <button class="btn btn-large btn-info">Buyer</button>
      <button class="btn btn-large btn-info">Homeowner</button>
    </div>
  </p>
</div>

<!-- Post Share Search -->
<div class="row-fluid">
  <div class="span12 offset4">
    <h1>How it works</h1>
  </div>
</div>

<hr>

<!-- Post Share Search -->
<div class="row-fluid">
  <div class="span4">
    <h2>Post</h2>
    <p>Provide your dream home criteria to current homeowners.</p>
  </div>
  <div class="span4">
    <h2>Share</h2>
    <p>Advertise your "dream" home criteria to the WORLD aka all the homeowners in your interested area</p>
 </div>
  <div class="span4">
    <h2>Search</h2>
    <p>Find "every" home in your home search not just the properties "on the market"</p>
  </div>
</div>

<hr>

<!-- Other -->
<div class="row-fluid">
  <div class="span4">
    <h3>About Us</h3>
      Our Mission |
      Our Team |
      Contact Us
  </div>
  <div class="span4">
    <h3>Follow Us</h3>
      <img src="assets/facebook.png" alt="facebook_icon">
      <img src="assets/twitter.png" alt="twitter_icon">
      <img src="assets/google.png" alt="facebook_icon">
  </div>
  <div class="span4">
    <h3>Fine Print</h3>
      Terms of Use |
      Privacy Policy
  </div>
</div>

<hr>
 
<!-- Post Share Search -->
<div class="row-fluid">
  <div class="span12 offset4">
    <p>&copy; HomeCanvasr 2013</p>
  </div>
</div>

app/views/layouts/_agent_links.html.erb
<ul class="dropdown-menu">
	<li><%= link_to 'Posts', posts_path %></li>
	<li><%= link_to 'Clients', clients_path %></li>
	<li><%= link_to 'Favorites', root_path %></li>
	<li><%= link_to 'Account Settings', edit_user_registration_path %></li>
	<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
</ul>

app/views/layouts/_buyer_links.html.erb
<ul class="dropdown-menu">
	<li><%= link_to 'Posts', root_path %></li>
	<li><%= link_to 'Favorites', root_path %></li>
	<li><%= link_to 'Account Settings', edit_user_registration_path %></li>
	<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
</ul>

app/views/layouts/_header.html.erb
<div id="container">
	<div class="navbar navbar-inverse">
	  <div class="navbar-inner">
	    <%= link_to "HomeCanvasr", root_path, class: "brand" %>
	    <div class = "pull-right">	
	    	<% if user_signed_in? %>
	      	<div class="btn-group">
	  				<a class="btn dropdown-toggle  btn-inverse" data-toggle="dropdown" href="#">
	    			<%= current_user.email %>
	    			<span class="caret"></span>
	  				</a>
	  					<%= render "layouts/agent_links" %>
					</div>    	
	    	<% else %>
	    	<a class="btn btn-inverse" href="/users/sign_in">Login</a>
	    	<% end %>
	   	</div>
	  </div>
	</div>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HomeCanvasr</title>
  <%= stylesheet_link_tag    "application" ,:media => "all" %>
  <%= javascript_include_tag "application"  %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">

    <%= render "layouts/header" %>

    <% flash.each do |name, msg| %>
      <div class="alert alert-info"> <%= content_tag :div, msg, id: "flash_#{name}" %> </div>
    <% end %>

    <%= yield %>
  
  </div>

</body>
</html>

app/views/posts/_agent.html.erb
<h2>Add New Post</h2>

<%= form_for @post do |f| %>

<% @post.errors.full_messages.each do |msg| %>
  <p><%= msg %></p>
<% end %>

<div class="field">
  <%= f.label "Client" %>
  <%= f.collection_select( :client_id, current_user.clients.order(:last_name), :id, :last_name, {:include_blank => false}) %>
</div>
<%= link_to "Add New Client", new_client_path, :id => "new_client" %>
</br>
</br>
  <div class="field">
    <%= f.label :state %>
    <%= f.collection_select( :state_id, State.order(:name), :id, :name, {:include_blank => true}) %>
  </div>
  <div class="field">
    <%= f.label :county %>

    <%= f.grouped_collection_select :county_id, State.order(:name), :counties, :name, :id, :name, include_blank: true %>

  </div>
  <div class="field">
    <%= f.label :city %>
   
   <%= f.grouped_collection_select :city_code, County.order(:name), :cities, :name, :city_code, :name, include_blank: true %>
  </div>
  </br>
  <p>
  <label for="amount">Price range:</label>
  <input type="text" id="amount" style="border: 0; color: #f6931f; font-weight: bold;" />
  </p>
<div id="slider-range" style="width:200px"></div>
<%= f.hidden_field :max_price, { :value => 0 } %>
<%= f.hidden_field :min_price, { :value => 0 } %>
</br>

<%= f.label :min_bed %>
<%= f.select :min_bed, [0,1,2,3,4,5] %>

<%= f.label :min_bath %>
<%= f.select :min_bath, [0,1,2,3,4,5] %>

<p>
  <label for="amount_square_feet">Minimum Size:</label>
  <input type="text" id="amount_square_feet" style="border: 0; color: #f6931f; font-weight: bold;" />
</p>
<div id="slider-range-sq-ft" style="width:200px"></div>
<%= f.hidden_field :min_sq_ft, { :value => 90000000 } %>
</br>
<p>
  <label for="amount_max_tax">Maximum Taxes:</label>
  <input type="text" id="amount_max_tax" style="border: 0; color: #f6931f; font-weight: bold;" />
  </p>
<div id="slider-range-max-tax" style="width:200px"></div>

<%= f.hidden_field :max_taxes, { :value => 0 } %>
</br>
<h4>Additional Options</h4>
<div class="field">
  <%= f.label :pool %>
  <%= f.check_box :pool %>
</div>
<div class="field">
  <%= f.label :attached_garage %>
  <%= f.check_box :attached_garage %>
</div>

  </br>
  </br>
  </br> 
    <%= f.submit "Submit", class: "btn-info"%>
<% end %>

app/views/posts/destroy.js.erb
$("#post_<%= @post.id %>").hide();

app/views/posts/edit.html.erb
<%= render 'posts/agent' %>

app/views/posts/edit.js.erb
$("#post_<%= @post.id %>").click(function() {
  alert("Handler for .click() called.");
});

app/views/posts/index.html.erb
<h2>My Posts</h2>

<table class="table table-striped">

	<tr>
		<th>My Client</th>
		<th>Date</th>
		<th>Town</th>
		<th>State</th>
		<th>Max Taxes</th>		
		<th>Max Price</th>
		<th>Min Bed</th>
		<th>Min Bath</th>
		<th>Manage</th>
		<th>Fetch Results</th>
	</tr>

	<% @posts.each do |p| %>

	<tr id=<%="post_#{p.id}"%> >
		<td><%= p.client_name %></td>
		<td><%= p.created_at.to_date %></td>
		<td><%= p.city_name %></td>
		<td><%= p.state_name %></td>
		<td><%= p.max_taxes %></td>		
		<td><%= p.max_price%></td>
		<td><%= p.min_bed %></td>
		<td><%= p.min_bath %></td>
		<td><%= link_to "Delete", p, method: :delete, :confirm => "Sure you want to delete this post?", remote: :true %> | <%= link_to "Edit", edit_post_path(p) %> </td>
		<td>Fetch Results</td>
	</tr>

	<% end %>
	
</table>

<a class="btn btn-info" href="/posts/new" >New Post</a>

app/views/posts/index.js.erb
$("#post_<%= @post.id %>").click(function() {
  alert("Handler for .click() called.");
});

app/views/posts/new.html.erb
<%= render 'posts/agent' %>

app/views/posts/show.html.erb
<table class="table table-striped">

	<tr>
		<th>State</th>
		<th>City</th>
		<th>Property Location</th>
		<th>Square Feet</th>
		<th><%= "#{Time.now.year - 1} Taxes"%></th>		
		<th>Net Taxable Value</th>
		<th>Tag</th>
	</tr>

 	
</table>